### ISSUE TITLE
Please include images

### ISSUE THREAD

**Issue by ChrisSchaller** [Jonas-Pamminger/Azure-Face-AI#1]
You need to include all the resources, in this case the images into the project so that we can follow along at home ;)
Happy to help, looks like you just need a nudge in the right direction

If you just dump them in a folder I can change the code to make it work.

**Comment by Jonas-Pamminger** [comment]
![Family1-Dad1](https://user-images.githubusercontent.com/85544687/126460208-4b1f7f7e-5ce9-4cfa-9c17-480b14a3c463.jpg)
![Family1-Dad2](https://user-images.githubusercontent.com/85544687/126460213-c432ceeb-5a12-40cc-ba7b-c5d34c77f25e.jpg)
![Family1-Daughter1](https://user-images.githubusercontent.com/85544687/126460214-912b0f57-281c-4930-8817-a6906d438c0d.jpg)
![Family1-Daughter2](https://user-images.githubusercontent.com/85544687/126460216-9f5a5b84-accf-430e-8ebf-06d11fbb41bb.jpg)
![Family1-Mom1](https://user-images.githubusercontent.com/85544687/126460218-8841efaa-ba9d-4c01-aa14-a8e20d7c42fc.jpg)
![Family1-Mom2](https://user-images.githubusercontent.com/85544687/126460219-da8f48ea-d576-4736-a012-afc53754466a.jpg)
![Family1-Son1](https://user-images.githubusercontent.com/85544687/126460221-478f6b29-0850-483a-8752-5dfa22d62df6.jpg)
![Family1-Son2](https://user-images.githubusercontent.com/85544687/126460223-082c570b-7602-4e6d-9b43-ce3e737567c1.jpg)

This pictures are the offical microsoft training pictures
![identification1](https://user-images.githubusercontent.com/85544687/126460282-f8a50e1c-6fa3-417f-92cc-e1cf90788b1c.jpg)
And this is the testing picture

Thanks for your help
